setup/urls.py
from django.contrib import admin
from django.urls import path
# from todos.views import home, todoListar
from todos.views import todoListarView,todoCriarView,todoAtualizarView
from todos.views import todoDeletarView
from todos.views import todoCompletarView

urlpatterns = [
    path("admin/", admin.site.urls),
    # rota que lista as tarefas
    # path("", todoListar),
    path("", todoListarView.as_view(template_name="todos/todolistar.html"),name='todo_listar'),   
    path("criar", todoCriarView.as_view(),name='todo_criar'),
    path("atualizar/<int:pk>", todoAtualizarView.as_view(),name='todo_atualizar'),
    path("deletar/<int:pk>", todoDeletarView.as_view(),name='todo_deletar'),
    path("completar/<int:pk>", todoCompletarView.as_view(),name='todo_completar')
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    titulo = models.CharField(verbose_name="Titulo da tarefa",max_length=150, null=False, blank=False)
    dtCriacao = models.DateTimeField(verbose_name="Data de Criação",auto_now_add=True, null=False, blank=False)
    dtFinalizado = models.DateTimeField(verbose_name="Data de Finalização",null=True, blank=True) 

todos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Todo
from django.views.generic import ListView, CreateView,UpdateView, DeleteView,View
from django.urls import reverse_lazy

from datetime import date
from django.shortcuts import redirect


# Create your views here.
def home(request):
    return render(request, "todos/home.html")

'''
def todoListar(request):
    # tarefas = [{
    #     'id':'1',
    #     'Tarefa':'comprar fraldas'
    # }]
    tarefas = Todo.objects.all()
    print(tarefas)
    return render(request, "todos/todolistar.html", {"tarefas": tarefas})
'''

class todoListarView(ListView):
    model = Todo #classe deve usar o modelo ToDo (.\todos\models.py)

class todoCriarView(CreateView):
    model = Todo
    fields = ["titulo","dtFinalizado"]  # Uma lista de campos que o usuario pode alterar
    success_url = reverse_lazy('todo_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Adicionar Tarefa'
        return context

class todoAtualizarView(UpdateView):
    model = Todo
    fields = ["titulo","dtFinalizado"]  # Uma lista de campos que o usuario pode alterar
    success_url = reverse_lazy('todo_listar')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo_pagina'] = 'Atualizar Tarefa'
        return context
    
class todoDeletarView(DeleteView):
    model = Todo
    success_url = reverse_lazy('todo_listar')

class todoCompletarView(View):
    def get(self,request,pk):
        tarefa = Todo.objects.get(pk=pk)
        tarefa.dtFinalizado = date.today()
        tarefa.save()
        return redirect('todo_listar')

todos/templates/padrao.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <title>      
        {% block titulo %}
        {% endblock %}
    </title>
  </head>
  <body>
    {% comment %}inicio da barra de navegação{% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">TODO</a>
      </div>
    </nav>
    {% comment %}Fim da barra de navegação{% endcomment %}

    <main class="container">
      <p class="text-start fs-4 fw-bold">
        {% block subtitulo %}
        {% endblock %}        
      </p>
      {% block conteudo %}
      {% endblock %}
    </main>

    {% comment %} inicio do modal de confirmacao de exclusao {% endcomment %}
    <!-- Modal -->
<div class="modal fade" id="modalDeletar" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Deseja excluir a tarefa abaixo</p>
          <p>ID: {{todo.id}}</p>
          <p>Descrição:{{todo.titulo}}</p>
        </div>
        <div class="modal-footer">
            <form method="POST">
                {% csrf_token %}
                <button type="button" onclick="window.location.href='{% url 'todo_listar' %}'" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </form>
        </div>
      </div>
    </div>
  </div>
    {% comment %} fim do modal de confirmação de exclusão {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

todos/templates/todos/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>rota: / </h1>
    <h1>Arquivo: home.html</h1>
    
</body>
</html>

todos/templates/todos/todo_confirm_delete.html
{% extends 'padrao.html' %}


{% block titulo %}
  Exclusao de tarefas
{% endblock %}


{% block subtitulo %}
  Exclusao de tarefas
{% endblock %}


{% block conteudo %}
  {% comment %}inicio do modal de confirmação de exclusão{% endcomment %}
  <script>
    window.addEventListener("load", (event) => {
       // Exibir o modal ao carregar a página
      $('#modalDeletar').modal('show')
    });
  </script>
  {% comment %}fim do modal de confirmação de exclusão{% endcomment %}
{% endblock %}

todos/templates/todos/todo_form.html
{% extends 'padrao.html' %}
{% load crispy_forms_tags %}

{% block titulo %}
  {{ titulo_pagina }}
{% endblock %}

{% block subtitulo %}
  {{ titulo_pagina }}
{% endblock %}

{% block conteudo %}
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="ENVIAR" />
  </form>
{% endblock %}

todos/templates/todos/todolistar.html
{% extends 'padrao.html' %}

{% block titulo %}
  Listagem de Tarefas
{% endblock %}

{% block subtitulo %}
  Listagem de Tarefas
{% endblock %}


{% block conteudo %}
      {% comment %} Inicio botao de criacao de tarefa {% endcomment %}
      <a href="{% url 'todo_criar' %}" 
         type="button" class="btn btn-success">Nova Tarefa</a>
      {% comment %} Fim botao de criacao de tarefa {% endcomment %}

      {% comment %}Inicio da tabela{% endcomment %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Titulo</th>
            <th scope="col">Criação</th>
            <th scope="col">Finalizacao</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% comment %} {% for tarefa in tarefas %} {% endcomment %}
          {% for tarefa in todo_list %}
            <tr>
              <th scope="row">{{ tarefa.id }}</th>
              <td>{{ tarefa.titulo }}</td>
              <td>{{ tarefa.dtCriacao|date:'SHORT_DATE_FORMAT' }}</td>
              <td>{{ tarefa.dtFinalizado|date:'SHORT_DATE_FORMAT'|default:'-' }}</td>
              {% comment %}botoes de acoes{% endcomment %}
              <td>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                  <button type="button" onclick="window.location.href='{% url 'todo_atualizar' pk=tarefa.pk %}'"  class="btn btn-warning">Editar</button>
                  <button type="button" onclick="window.location.href='{% url 'todo_completar' pk=tarefa.pk %}'"  class="btn btn-info">Completar</button>
                  <button type="button" onclick="window.location.href='{% url 'todo_deletar' pk=tarefa.pk %}'" class="btn btn-danger">Excluir</button>
                </div>
              </td>
            
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% comment %}fim da tabela{% endcomment %}
{% endblock%}